const REQUEST_LOAN_INFORMATION = 'app/loan/requst';
const REQUEST_LOAN_INFORMATION_FAILURE = 'app/loan/failure';
const REQUEST_LOAN_INFORMATION_SUCCESS = 'app/loan/success';

export default {
    REQUEST_LOAN_INFORMATION,
    REQUEST_LOAN_INFORMATION_FAILURE,
    REQUEST_LOAN_INFORMATION_SUCCESS
};